add cilium networkpolicy
kubeovn/docs pull request #10
Opened 2022-07-18 06:38 UTC by hongzhen-ma

2022-07-19 07:22 UTC, oilbeater requested changes

2022-07-19 07:22 UTC, oilbeater commented on docs/advance/cilium-networkpolicy.md
> +Kube-OVN 当前已经支持与 Cilium 集成，具体操作可以参考 [Cilium集成](https://kubeovn.github.io/docs/advance/with-cilium/)
```suggestion
Kube-OVN 当前已经支持与 Cilium 集成，具体操作可以参考 [Cilium集成](with-cilium.md)。
```

2022-07-19 07:22 UTC, oilbeater commented on docs/advance/cilium-networkpolicy.md
> +```yaml
```suggestion
```bash
```

2022-07-19 07:22 UTC, oilbeater commented on docs/advance/cilium-networkpolicy.md
> +创建 namespace test，分别在 `default` 和 `test` namespace 下部署测试应用，test namespace 下指定 label `app=test` 的 Pod，为测试访问的目的 Pod，指定其他 label `app=dynamic` 和 `app=test1` 的 Pod 为发起访问测试的 Pod。
需要给出对应 yaml

2022-07-19 07:22 UTC, oilbeater commented on docs/advance/cilium-networkpolicy.md
> +```yaml
```suggestion
```bash
```

2022-07-19 07:22 UTC, oilbeater commented on docs/advance/cilium-networkpolicy.md
> +```yaml
```suggestion
```bash
```

2022-07-19 07:22 UTC, oilbeater commented on docs/advance/cilium-networkpolicy.md
> +```yaml
后面类似的问题也要修改

2022-07-21 06:03 UTC, hongzhen-ma commented on docs/advance/cilium-networkpolicy.md
> +```yaml
已修改

2022-07-21 06:04 UTC, hongzhen-ma commented on docs/advance/cilium-networkpolicy.md
> +创建 namespace test，分别在 `default` 和 `test` namespace 下部署测试应用，test namespace 下指定 label `app=test` 的 Pod，为测试访问的目的 Pod，指定其他 label `app=dynamic` 和 `app=test1` 的 Pod 为发起访问测试的 Pod。
已修改

2022-07-21 06:04 UTC, hongzhen-ma commented on docs/advance/cilium-networkpolicy.md
> +```yaml
已修改

2022-07-21 06:04 UTC, hongzhen-ma commented on docs/advance/cilium-networkpolicy.md
> +```yaml
已修改

2022-07-21 06:05 UTC, hongzhen-ma commented on docs/advance/cilium-networkpolicy.md
> +Kube-OVN 当前已经支持与 Cilium 集成，具体操作可以参考 [Cilium集成](https://kubeovn.github.io/docs/advance/with-cilium/)
这么写的话，能点击跳转吗？

2022-07-21 06:14 UTC, hongzhen-ma commented on docs/advance/cilium-networkpolicy.md
> +Kube-OVN 当前已经支持与 Cilium 集成，具体操作可以参考 [Cilium集成](https://kubeovn.github.io/docs/advance/with-cilium/)
已修改

2022-08-02 02:45 UTC, oilbeater requested changes

2022-08-02 02:45 UTC, oilbeater commented on docs/advance/cilium-hubble-observe.md
> +apple@bogon cilium % cilium status
bash 命令以 `#` 开始，不要带个人机器的信息

2022-08-02 02:45 UTC, oilbeater commented on docs/advance/cilium-hubble-observe.md
> +更多详细的观测信息，可以执行 `hubble help observe` 命令查看 hubble CLI 的详细使用方式。
```suggestion
更多详细的观测信息，可以执行 `hubble help observe` 命令查看 Hubble CLI 的详细使用方式。
```

2022-08-02 02:45 UTC, oilbeater commented on docs/advance/cilium-networkpolicy.md
> +在有网络策略规则匹配的情况下，只有`同一个 Namespace` 的 Pod ，才可以按照规则进行访问，默认拒绝`其他 Namespace` 的 Pod 进行访问。
```suggestion
在有网络策略规则匹配的情况下，只有**同一个 Namespace** 的 Pod ，才可以按照规则进行访问，默认拒绝**其他 Namespace** 的 Pod 进行访问。
```

2022-08-02 02:45 UTC, oilbeater commented on docs/advance/cilium-networkpolicy.md
> +使用标准的 k8s 网络策略 [networkpolicy](https://kubernetes.io/zh-cn/docs/concepts/services-networking/network-policies/)，测试结果显示 Cilium 同样将访问限制在同一个 Namespace 内，跨 Namespace 的访问是禁止的。
```suggestion
使用标准的 Kubernetes 网络策略 [networkpolicy](https://kubernetes.io/zh-cn/docs/concepts/services-networking/network-policies/)，测试结果显示 Cilium 同样将访问限制在同一个 Namespace 内，跨 Namespace 的访问是禁止的。
```

2022-08-02 02:45 UTC, oilbeater commented on docs/advance/cilium-networkpolicy.md
> +chaining 模式下，L7 网络策略目前是存在问题的。在 cilium 官方文档中，对这种情况给出了说明，参考 [Generic Veth Chaining](https://docs.cilium.io/en/stable/gettingstarted/cni-chaining-generic-veth/)。
```suggestion
chaining 模式下，L7 网络策略目前是存在问题的。在 Cilium 官方文档中，对这种情况给出了说明，参考 [Generic Veth Chaining](https://docs.cilium.io/en/stable/gettingstarted/cni-chaining-generic-veth/)。
```

2022-08-02 02:45 UTC, oilbeater commented on docs/advance/cilium-networkpolicy.md
> +这点与 Kube-OVN 实现是不同的。Kube-OVN 支持标准的 k8s 网络策略，限制了具体 Namespace 下的`目的 Pod`，但是对源地址 Pod，是没有 Namespace 限制的，任何 Namespace 下符合限制规则的 Pod，都可以实现对目的 Pod 的访问。
```suggestion
这点与 Kube-OVN 实现是不同的。Kube-OVN 支持标准的 k8s 网络策略，限制了具体 Namespace 下的**目的 Pod**，但是对源地址 Pod，是没有 Namespace 限制的，任何 Namespace 下符合限制规则的 Pod，都可以实现对目的 Pod 的访问。
```

2022-08-02 06:19 UTC, hongzhen-ma commented on docs/advance/cilium-hubble-observe.md
> +apple@bogon cilium % cilium status
排查了文档内涉及bash的地方，都做了修改

2022-08-02 06:19 UTC, hongzhen-ma commented on docs/advance/cilium-hubble-observe.md
> +更多详细的观测信息，可以执行 `hubble help observe` 命令查看 hubble CLI 的详细使用方式。
已修改

2022-08-02 06:19 UTC, hongzhen-ma commented on docs/advance/cilium-networkpolicy.md
> +在有网络策略规则匹配的情况下，只有`同一个 Namespace` 的 Pod ，才可以按照规则进行访问，默认拒绝`其他 Namespace` 的 Pod 进行访问。
已修改

2022-08-02 06:19 UTC, hongzhen-ma commented on docs/advance/cilium-networkpolicy.md
> +使用标准的 k8s 网络策略 [networkpolicy](https://kubernetes.io/zh-cn/docs/concepts/services-networking/network-policies/)，测试结果显示 Cilium 同样将访问限制在同一个 Namespace 内，跨 Namespace 的访问是禁止的。
已修改

2022-08-02 06:20 UTC, hongzhen-ma commented on docs/advance/cilium-networkpolicy.md
> +chaining 模式下，L7 网络策略目前是存在问题的。在 cilium 官方文档中，对这种情况给出了说明，参考 [Generic Veth Chaining](https://docs.cilium.io/en/stable/gettingstarted/cni-chaining-generic-veth/)。
已修改

2022-08-02 06:27 UTC, oilbeater approved these changes

2022-08-02 06:27 UTC, merged