kubectl ko perf diagnose
kubeovn/docs pull request #104
Opened 2023-06-29 09:36 UTC by changluyi

- [ ] Make sure you have followed the [Document Convention](../docs/reference/document-convention.md).

2023-06-30 02:06 UTC, oilbeater requested changes

2023-06-30 02:06 UTC, oilbeater commented on docs/ops/kubectl-ko.en.md
> +If the target of diagnose is specified as IPPorts, the script will let each `kube-ovn-pinger` pod detect whether the target protocol, IP, and Port are reachable
```suggestion
If the target of diagnose is specified as IPPorts, the script will let each `kube-ovn-pinger` pod detect whether the target protocol, IP, and Port are reachable.
```

2023-06-30 02:06 UTC, oilbeater commented on docs/ops/kubectl-ko.md
> +如果 diagnose 的目标指定为 IPPorts 该脚本会让每个 `kube-ovn-pinger` pod 去探测目标协议，IP，Port 是否可达
```suggestion
如果 diagnose 的目标指定为 IPPorts 该脚本会让每个 `kube-ovn-pinger` pod 去探测目标协议，IP，Port 是否可达。
```

2023-07-13 06:41 UTC, changluyi commented on docs/ops/kubectl-ko.en.md
> +If the target of diagnose is specified as IPPorts, the script will let each `kube-ovn-pinger` pod detect whether the target protocol, IP, and Port are reachable
fixed

2023-07-13 06:41 UTC, changluyi commented on docs/ops/kubectl-ko.md
> +如果 diagnose 的目标指定为 IPPorts 该脚本会让每个 `kube-ovn-pinger` pod 去探测目标协议，IP，Port 是否可达
fixed

2023-07-13 07:09 UTC, oilbeater commented
lint failed

2023-07-13 07:57 UTC, changluyi commented
> lint failed

fixed

2023-07-13 07:58 UTC, changluyi commented
> lint failed

fixed

2023-07-13 08:08 UTC, merged