update ovn nats
kubeovn/docs pull request #130
Opened 2023-10-23 08:57 UTC by bobz965

- [ ] Make sure you have followed the [Document Convention](../docs/reference/document-convention.md).

https://github.com/kubeovn/kube-ovn/pull/3313

2023-10-23 09:52 UTC, bobz965 commented
hi @oilbeater ，  lint 检测的错误好像是基于已经不存在的文件产生的，感觉需要清理下

2023-10-24 02:50 UTC, oilbeater requested changes

2023-10-24 02:50 UTC, oilbeater commented on mkdocs.yml
> +      - 自定义 VPC 内部负载均衡(健康检查): 'advance/vpc-internal-lb-hc.md'
不需要改名字

2023-10-24 03:24 UTC, bobz965 commented on mkdocs.yml
> +      - 自定义 VPC 内部负载均衡(健康检查): 'advance/vpc-internal-lb-hc.md'
ok

2023-10-25 01:43 UTC, oilbeater approved these changes

2023-10-25 01:43 UTC, merged