update: multus usage example
kubeovn/docs pull request #159
Opened 2024-02-26 03:00 UTC by zcq98

- [x] Make sure you have followed the [Document Convention](../docs/reference/document-convention.md).

2024-02-26 03:19 UTC, bobz965 commented on docs/advance/multi-nic.md
> +创建一个 Kube-OVN Subnet,设置对应的 `cidrBlock` 和 `exclude_ips`，`provider` 应该设置为对应的 NetworkAttachmentDefinition 的 `<name>.<namespace>`，
```suggestion
创建一个 Kube-OVN Subnet, 设置对应的 `cidrBlock` 和 `exclude_ips`，`provider` 应该设置为对应的 NetworkAttachmentDefinition 的 `<name>.<namespace>`，
```

2024-02-26 03:19 UTC, bobz965 commented on docs/advance/multi-nic.md
> +对于使用 macvlan 作为主网卡的 Pod，只需要添加如下 annotation `v1.multus-cni.io/default-network`,取值为对应的 NetworkAttachmentDefinition 的 `<namespace>/<name>`：
```suggestion
对于使用 macvlan 作为主网卡的 Pod，只需要添加如下 annotation `v1.multus-cni.io/default-network`, 取值为对应的 NetworkAttachmentDefinition 的 `<namespace>/<name>`：
```

2024-02-26 03:19 UTC, bobz965 commented on docs/advance/multi-nic.md
> +对于地址随机分配的 Pod，只需要添加如下 annotation `k8s.v1.cni.cncf.io/networks`,取值为对应的 NetworkAttachmentDefinition 的 `<namespace>/<name>`：
```suggestion
对于地址随机分配的 Pod，只需要添加如下 annotation `k8s.v1.cni.cncf.io/networks`, 取值为对应的 NetworkAttachmentDefinition 的 `<namespace>/<name>`：
```

2024-02-28 02:57 UTC, oilbeater requested changes

2024-02-28 02:57 UTC, oilbeater commented on docs/advance/multi-nic.en.md
这个文件是不是改错了

2024-02-28 03:30 UTC, zcq98 commented on docs/advance/multi-nic.en.md
改错了，已修正

2024-02-28 08:07 UTC, bobz965 approved these changes

2024-02-28 10:33 UTC, oilbeater approved these changes

2024-02-28 10:34 UTC, merged