feat: add manual restore and notice
kubeovn/docs pull request #3
Opened 2022-07-05 04:03 UTC by lut777

2022-07-05 05:36 UTC, oilbeater requested changes

2022-07-05 05:36 UTC, oilbeater commented on docs/advance/with-ovn-ic.md
> +**注意:** 为了保证操作的正确性,  `ovn-ic-config` 这个 configmap 不允许修改. 如有参数需要变更, 请删除该 ovn-configmap , 修改后再应用此 configmap.
```suggestion
**注意：** 为了保证操作的正确性，`ovn-ic-config` 这个 ConfigMap 不允许修改。如有参数需要变更，请删除该 ConfigMap，修改后再应用此 ConfigMap。
```

2022-07-05 05:36 UTC, oilbeater commented on docs/advance/with-ovn-ic.md
> +某些情况下, 例如误编辑了 `ovn-ic-config` 的配置时, OVN-IC 可能出现配置异常. 同时由于端口被占用, 可能重配置无法恢复. 因此需要手动重置环境.
```suggestion
某些情况下，例如误编辑了 `ovn-ic-config` 的配置时, OVN-IC 可能出现配置异常。同时由于端口被占用, 可能重配置无法恢复，因此需要手动重置环境。
```

2022-07-05 05:36 UTC, oilbeater commented on docs/advance/with-ovn-ic.md
> +在这种情况下. 可以按下列操作重置环境:
```suggestion
在这种情况下，可以按下列操作重置环境：
```

2022-07-05 05:36 UTC, oilbeater commented on docs/advance/with-ovn-ic.md
> +# 处理完毕后退出. 然后重新部署 ovn-ic-config 即可.
先删除 `ovn-ic-config` 避免被定期重建？

2022-07-07 03:30 UTC, lut777 commented on docs/advance/with-ovn-ic.md
> +# 处理完毕后退出. 然后重新部署 ovn-ic-config 即可.
这个东西的pr好像是一次性的. 通过后再改吧?

2022-07-07 03:47 UTC, lut777 commented on docs/advance/with-ovn-ic.md
> +# 处理完毕后退出. 然后重新部署 ovn-ic-config 即可.
在操作步骤的第一行加入了删除 ovn-ic-config 的操作及说明.

2022-07-07 03:48 UTC, oilbeater approved these changes

2022-07-07 03:48 UTC, merged