add loadbalancer service support in default vpc
kubeovn/docs pull request #5
Opened 2022-07-08 07:19 UTC by hongzhen-ma

2022-07-15 03:34 UTC, oilbeater requested changes

2022-07-15 03:34 UTC, oilbeater commented on docs/guide/loadbalancer-service.md
> +
需要标题

2022-07-15 03:34 UTC, oilbeater commented on docs/guide/loadbalancer-service.md
> +
数字，字母和中文间需要有空格

2022-07-15 03:34 UTC, oilbeater commented on docs/guide/loadbalancer-service.md
> +# 默认Vpc LoadBalancer Service配置步骤
二级标题

2022-07-15 03:34 UTC, oilbeater commented on docs/guide/loadbalancer-service.md
> +修改kube-system namespace下的deployment kube-ovn-controller，在args中增加参数 --enable-lb-svc=true，开启功能开关，该参数默认为false。
参考其他地方开启功能的格式，需要列出 yaml 格式

2022-07-15 03:34 UTC, oilbeater commented on docs/guide/loadbalancer-service.md
> +参考以下yaml内容，创建net-attach-def 资源
```suggestion
参考以下 yaml 内容，创建 `net-attach-def` 资源：
```

2022-07-15 03:34 UTC, oilbeater commented on docs/guide/loadbalancer-service.md
> +## 创建subnet
```suggestion
### 创建 Subnet
```

2022-07-15 03:34 UTC, oilbeater commented on docs/guide/loadbalancer-service.md
> +使用以下yaml，创建新子网
```suggestion
使用以下 yaml，创建新子网：
```

2022-07-15 03:34 UTC, oilbeater commented on docs/guide/loadbalancer-service.md
> +```
```suggestion
```yaml
```

markdown 代码格式需要声明代码类型是 yaml 或者 bash

2022-07-18 02:05 UTC, hongzhen-ma commented on docs/guide/loadbalancer-service.md
> +
已修改

2022-07-18 02:18 UTC, hongzhen-ma commented on docs/guide/loadbalancer-service.md
> +```
涉及配置部分已经添加，展示部分没有添加 yaml 字样

2022-07-18 02:26 UTC, hongzhen-ma commented on docs/guide/loadbalancer-service.md
> +# 默认Vpc LoadBalancer Service配置步骤
已修改

2022-07-18 02:27 UTC, hongzhen-ma commented on docs/guide/loadbalancer-service.md
> +修改kube-system namespace下的deployment kube-ovn-controller，在args中增加参数 --enable-lb-svc=true，开启功能开关，该参数默认为false。
已修改

2022-07-18 02:27 UTC, hongzhen-ma commented on docs/guide/loadbalancer-service.md
> +参考以下yaml内容，创建net-attach-def 资源
已修改

2022-07-18 02:27 UTC, hongzhen-ma commented on docs/guide/loadbalancer-service.md
> +## 创建subnet
已修改

2022-07-18 02:27 UTC, hongzhen-ma commented on docs/guide/loadbalancer-service.md
> +使用以下yaml，创建新子网
已修改

2022-07-18 06:31 UTC, hongzhen-ma commented on docs/guide/loadbalancer-service.md
> +```
全都加了yaml 字样

2022-07-19 07:36 UTC, merged