Create ovn-ipsec.md
kubeovn/docs pull request #57
Opened 2023-04-04 10:36 UTC by changluyi

- [ ] Make sure you have followed the [Document Convention](../docs/reference/document-convention.md).

2023-04-12 02:00 UTC, oilbeater requested changes

2023-04-12 02:00 UTC, oilbeater commented on docs/advance/ovn-ipsec.md
> +# 使用 ovn ipsec 加密 ovn 内部节点之间的通信
```suggestion
# 使用 ipsec 加密节点间通信
```

2023-04-12 02:00 UTC, oilbeater commented on docs/advance/ovn-ipsec.md
> +从 kube-ovn 源码拷贝脚本，路径是： dist/image/ipsec.sh，执行命令如下，该脚本会调用 ovs-pki 生成和分配加密需要的证书：
kube-ovn -> Kube-OVN

需要给出脚本的下载链接

2023-04-12 02:00 UTC, oilbeater commented on docs/advance/ovn-ipsec.md
> +执行完毕后，节点之间会协商一段时间建立 ipsec 隧道，经验值是十几秒到一分钟之间，可以通过如下命令来查看 ipsec 状态
```suggestion
执行完毕后，节点之间会协商一段时间建立 ipsec 隧道，经验值是十几秒到一分钟之间，可以通过如下命令来查看 ipsec 状态：
```

2023-04-12 02:03 UTC, oilbeater requested changes

2023-04-12 02:03 UTC, oilbeater commented on docs/advance/ovn-ipsec.md
> +sh ipsec.sh init
需要改成 bash。sh 报错 `ipsec.sh: 2: set: Illegal option -o pipefail`

2023-04-12 07:22 UTC, changluyi commented on docs/advance/ovn-ipsec.md
> +sh ipsec.sh init
已修复以上，包括英文文档

2023-04-13 02:12 UTC, oilbeater requested changes

2023-04-13 02:12 UTC, oilbeater commented on docs/advance/ovn-ipsec.md
> +该功能从 v1.10.11 和 v1.11.4 后开始支持，kernel 版本至少是 3.10.0 以上
```suggestion
该功能从 v1.10.11 和 v1.11.4 后开始支持，kernel 版本至少是 3.10.0 以上。
```

2023-04-13 02:12 UTC, oilbeater commented on docs/advance/ovn-ipsec.md
> +从 kube-ovn 源码拷贝脚本 [ipsec.sh](https://github.com/kubeovn/kube-ovn/blob/master/dist/images/ipsec.sh)，执行命令如下，该脚本会调用 ovs-pki 生成和分配加密需要的证书：
```suggestion
从 Kube-OVN 源码拷贝脚本 [ipsec.sh](https://raw.githubusercontent.com/kubeovn/kube-ovn/master/dist/images/ipsec.sh)，执行命令如下，该脚本会调用 ovs-pki 生成和分配加密需要的证书：
```

2023-04-14 03:17 UTC, changluyi commented on docs/advance/ovn-ipsec.md
> +从 kube-ovn 源码拷贝脚本 [ipsec.sh](https://github.com/kubeovn/kube-ovn/blob/master/dist/images/ipsec.sh)，执行命令如下，该脚本会调用 ovs-pki 生成和分配加密需要的证书：
已修复以上

2023-04-18 05:34 UTC, oilbeater approved these changes

2023-04-18 05:34 UTC, merged