Create node-local-dns.md
kubeovn/docs pull request #74
Opened 2023-05-04 02:42 UTC by changluyi

- [ ] Make sure you have followed the [Document Convention](../docs/reference/document-convention.md).

2023-05-04 09:30 UTC, oilbeater requested changes

2023-05-04 09:30 UTC, oilbeater commented on docs/advance/node-local-dns.md
> +该步骤参考 k8s 官网配置 [nodelocaldnscache](https://kubernetes.io/zh-cn/docs/tasks/administer-cluster/nodelocaldns/)。
k8s -> Kubernetes

2023-05-04 09:30 UTC, oilbeater commented on docs/advance/node-local-dns.md
> +NodeLocal DNSCache 是通过集群节点上作为 DaemonSet 运行 DNS 缓存来提高集群 DNS 性能，该功能也可以和 kube-ovn 适配。
kube-ovn -> Kube-OVN

2023-05-04 09:30 UTC, oilbeater commented on docs/advance/node-local-dns.md
> +这步原因是让 pod 重新生成 /etc/resolv.conf 让 nameserver 指向本地 dns ip，如果没有重建 pod 的 nameserver 将仍然使用集群的 dns cluster ip。同时 u2o 开关如果开启也需要重建 pod 来重新生成 pod 网关。
```suggestion
这步原因是让 pod 重新生成 `/etc/resolv.conf` 让 nameserver 指向本地 DNS IP，如果没有重建 Pod 的 nameserver 将仍然使用集群的 DNS ClusterIP。同时 u2o 开关如果开启也需要重建 pod 来重新生成 pod 网关。
```

2023-05-04 12:08 UTC, changluyi commented on docs/advance/node-local-dns.md
> +这步原因是让 pod 重新生成 /etc/resolv.conf 让 nameserver 指向本地 dns ip，如果没有重建 pod 的 nameserver 将仍然使用集群的 dns cluster ip。同时 u2o 开关如果开启也需要重建 pod 来重新生成 pod 网关。
fixed all

2023-05-04 14:51 UTC, oilbeater requested changes

2023-05-04 14:51 UTC, oilbeater commented on docs/advance/node-local-dns.md
> +### kube-OVN 相应 DNS 配置
```suggestion
### Kube-OVN 相应 DNS 配置
```

2023-05-05 02:07 UTC, changluyi commented on docs/advance/node-local-dns.md
> +### kube-OVN 相应 DNS 配置
fixed

2023-05-05 05:02 UTC, merged